[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
ADD makepkg.conf /etc/makepkg.conf
ADD pacman.conf /etc/pacman.conf
ADD localtime /etc/localtime
ADD bin/* /usr/local/bin

# Base setup
RUN echo -e '[multilib]\n\
Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
RUN pacman -Syyyu schedtool base-devel git distcc --asdeps --noconfirm

# Setup makepkg to run as root
RUN sed -i 's/.*exit \$E_ROOT.*//g' /usr/bin/makepkg

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/amdgpu-pro-installer.git 
WORKDIR amdgpu-pro-installer
RUN yes | low-prio makepkg -si --noconfirm

# Cleanup
RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*

WORKDIR /
'''

[run]
dri = true
devices = ['/dev/kfd']
args = ['--group-add', 'video']
