[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/opencl-amd
RUN pacman -Syu blender --noconfirm
RUN rm -rf /var/cache/*
RUN id 1000 || useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/blender"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = true
dbus = false
net = false
uidmap = true
home = true
volumes = ['/home/julio/Videos:/home/user/Videos', '/home/julio/Downloads:/home/user/Downloads']
devices = ['/dev/kfd']
args = ['--group-add', 'video']
env = []
ports = []
