[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu element-desktop ttf-dejavu --noconfirm
RUN rm -rf /var/cache/*

CMD ["/usr/bin/element-desktop", "--hidden"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []
