[build]
instructions = '''
FROM localhost/sandman/base/arch_build

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/geekbench.git 
WORKDIR geekbench

RUN pacman -S $(/bin/sh -c 'source /tmp/build/geekbench/PKGBUILD ; echo ${depends[@]}') --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U *.tar.zst --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/pacman/pkg
RUN rm -rf /tmp/build
CMD "/usr/bin/geekbench"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = false
dbus = false
net = true
uidmap = true
volumes = []
devices = []
env = []

ports = []
