[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_build

RUN echo '1' | sudo -u user gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 031F7104E932F7BD7416E7F6D2845E1305D6E801
RUN echo '1' | sudo -u user gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 2954CC8585E27A3F
RUN echo '1' | gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 031F7104E932F7BD7416E7F6D2845E1305D6E801
RUN echo '1' | gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 2954CC8585E27A3F
RUN pacman-key --init
RUN pacman-key --recv-keys 2954CC8585E27A3F
RUN pacman-key --lsign-key 2954CC8585E27A3F
#RUN pacman-key --refresh-keys

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/librewolf-bin.git 
WORKDIR librewolf-bin

RUN pacman -S ffmpeg4.4 libva-mesa-driver mesa-vdpau libfido2 --noconfirm

RUN pacman -S $(/bin/sh -c 'source /tmp/build/librewolf-bin/PKGBUILD ; echo ${depends[@]}') --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /tmp/build/librewolf-bin/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg
RUN pacman -U *.tar.zst --noconfirm 

WORKDIR /home/user
RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD "/usr/bin/librewolf"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
pipewire = false
dbus = true
net = true
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads',
]
fonts = true
devices = [
	'/dev/kfd', 
]
UsbDevices = ["1050:0116"]
env = [
	#"MOZ_WEBRENDER=1", 
	"MOZ_USE_XINPUT2=1",
	"MOZ_DISABLE_RDD_SANDBOX=1"
	#'MOZ_LOG="PlatformDecoderModule:5"'
]
ports = []

