[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu obsidian --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/obsidian"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = false
dbus = false
network = "slirp4netns"
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  '/usr/share/fonts:/usr/share/fonts:ro'
]
devices = []
env = []
ports = []
args = []
