[build]
instructions = '''
FROM localhost/sandman/base/arch_user
RUN pacman -Syu obsidian --noconfirm
RUN rm -rf /var/cache/*
CMD "/usr/bin/obsidian"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = false
dbus = false
network = "slirp4netns"
uidmap = true
home = true
fonts = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads'
]
devices = []
env = []
ports = []
args = []
