[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_build

RUN pacman -S nss at-spi2-core libcups libdrm gdk-pixbuf2 gtk3 --noconfirm

RUN mkdir -p /tmp/build
WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/podman-desktop-bin.git 
WORKDIR podman-desktop-bin

#RUN pacman -S $(/bin/sh -c 'source /tmp/build/podman-desktop-bin/PKGBUILD ; echo ${depends[@]}') --asdeps --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /tmp/build/podman-desktop-bin/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U *.tar.zst --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD ["/usr/bin/podman-desktop"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = false
dbus = true
network = "host"
uidmap = true
home = true
fonts = true
volumes = [
	"/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock"
]
devices = []
env = []
ports = []

