[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_build

RUN pacman -S alsa-lib libpulse libappindicator-gtk3 --noconfirm

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/slack-desktop.git 
WORKDIR slack-desktop

RUN pacman -S $(/bin/sh -c 'source /tmp/build/slack-desktop/PKGBUILD ; echo ${depends[@]}') --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U *.tar.zst --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/pacman/pkg
RUN rm -rf /tmp/build
CMD "/usr/bin/slack"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
fonts = true
volumes = []
devices = []
env = []
ports = []
