[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN dpkg --add-architecture i386

RUN apt update
RUN apt dist-upgrade -y
RUN apt install steam lib32gcc-s1 xserver-xorg-video-amdgpu adwaita-icon-theme-full schedtool -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
RUN apt autoremove -y
RUN apt clean -y
CMD ["/usr/bin/schedtool", "-a", "0,1,2,3,4,5,6,7", "-e", "/usr/games/steam"]
#CMD ["/usr/games/steam"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
volumes = []
devices = []
env = ["mesa_glthread=true"]
ports = []

[Limits.CPU]
#Cpus = "0,1,2,3,4,5,6,7"
