[build]
instructions = '''
FROM localhost/sandman/base/arch_build

# NVM

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/nvm.git 
WORKDIR nvm

#RUN pacman -S $(/bin/sh -c 'source /tmp/build/nvm/PKGBUILD ; echo ${depends[@]}') --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /tmp/build/nvm/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U $(/bin/sh -c 'source /tmp/build/nvm/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm

# Tidal

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/tidal-hifi.git 
WORKDIR tidal-hifi

RUN pacman -S $(/bin/sh -c 'source /tmp/build/tidal-hifi/PKGBUILD ; echo ${depends[@]}') --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /tmp/build/tidal-hifi/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U $(/bin/sh -c 'source /tmp/build/tidal-hifi/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm

RUN pacman -S alsa-lib pulseaudio --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD ["/usr/bin/tidal-hifi"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []

