[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu base-devel git distcc --asdeps --noconfirm
RUN pacman -S pulseaudio pipewire fontconfig ttf-dejavu xcftools --noconfirm

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

# Speedup compilation
ADD makepkg.conf /etc/makepkg.conf
#RUN echo "MAKEFLAGS=-j$(nproc)" >> /etc/makepkg.conf

# vasm

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/vasm.git 
WORKDIR vasm

RUN chown -R user:user /home/user
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U *.tar.zst --noconfirm

# python2-pillow

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/python2-pillow.git 
WORKDIR python2-pillow

RUN pacman -S $(/bin/sh -c 'source /home/user/python2-pillow/PKGBUILD ; echo ${depends[@]}') --noconfirm
RUN pacman -S $(/bin/sh -c 'source /home/user/python2-pillow/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /home/user
RUN nice -n 19 sudo -u user makepkg 
#RUN pacman -U $(/bin/sh -c 'source /home/user/python2-pillow/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm
RUN pacman -U *.tar.zst --noconfirm

# blastem

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/blastem.git 
WORKDIR blastem

RUN pacman -S $(/bin/sh -c 'source /home/user/blastem/PKGBUILD ; echo ${depends[@]}') --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /home/user/blastem/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm
RUN pacman -S mercurial --asdeps --noconfirm

RUN chown -R user:user /home/user
RUN nice -n 19 sudo -u user makepkg 
#RUN pacman -U $(/bin/sh -c 'source /home/user/blastem/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm
RUN pacman -U *.tar.zst --noconfirm

# Cleanup

WORKDIR /home/user
#RUN pacman -Rns $(/bin/sh -c 'source /home/user/python2-pillow/PKGBUILD ; echo ${makedepends[@]}') --noconfirm
#RUN pacman -Rns $(/bin/sh -c 'source /home/user/blastem/PKGBUILD ; echo ${makedepends[@]}') --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /home/user/blastem
CMD ["/usr/bin/blastem"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = true
dbus = false
net = false
uidmap = true
volumes = ['/home/julio/Games/genesis:/home/user']
devices = []
env = []
ports = []

