[build]
instructions = '''
FROM docker.io/fedora
RUN dnf update -y
RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
RUN rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
RUN dnf install -y brave-browser

RUN dnf clean all

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*

CMD "/usr/bin/brave-browser"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = true
dbus = false
network = "slirp4netns"
uidmap = true
volumes = []
devices = []
env = []
ports = []
