[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu chromium libva-mesa-driver mesa-vdpau pulseaudio alsa-lib --noconfirm

RUN rm -rf /var/cache/*
CMD ["/usr/bin/chromium", "--enable-features=VaapiVideoDecoder", "--use-gl=egl"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
network = "slirp4netns"
uidmap = true
volumes = []
devices = []
env = []
ports = []
args = []
