[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_dev

RUN pacman -Syu code ttf-hack --noconfirm

WORKDIR /home/user

RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*
#CMD ["/usr/bin/code", "--verbose", "--enable-features=UseOzonePlatform", "--ozone-platform=wayland"]
CMD ["/usr/bin/code", "--verbose"]
#CMD ["electron19", "/usr/lib/code/out/cli.js", "/usr/lib/code/code.js", "--ozone-platform=wayland"]
#CMD ["bash", "-c", "/usr/bin/code --ozone-platform=wayland && while pgrep -f [e]lectron > /dev/null; do sleep 5; done"]
'''

[run]
name = "code"
x11 = true
wayland = true
dri = true
ipc = true
pulseaudio = true
dbus = true
network = "host"
uidmap = true
home = true
fonts = false
volumes = [
	"/home/julio/Repos:/home/user/Repos",
	#'/home/julio/.local/share/fonts:/home/user/.local/share/fonts:ro',
	"/home/julio/Projects:/home/user/Projects",
	"/home/julio/Downloads:/home/user/Downloads",
	"/home/julio/Sandman/kali:/home/user/Kali",
	#"/tmp/makepkg:/tmp/makepkg",
	#"/home/julio/Kali:/home/user/Kali",
]
devices = []
env = [
	"GOPATH=/home/user/go",
	"PATH=/home/user/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
	"XDG_RUNTIME_DIR=/run/user/1000",
]
ports = []
args = []
