[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu discord ttf-dejavu ttf-joypixels libpulse alsa-lib flatpak-xdg-utils --noconfirm
RUN rm -rf /var/cache/*
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD ["/opt/discord/Discord", "--start-minimized"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
volumes = [
	'/home/julio/Downloads:/home/user/Downloads', 
	'/home/julio/Pictures:/home/user/Pictures:ro', 
	'/home/julio/Pictures:/home/julio/Pictures:ro', 
	'/home/julio/Videos:/home/user/Videos:ro',
	'/home/julio/Videos:/home/julio/Videos:ro',
]
#devices = ['/dev/video0']
#devices = []
env = []
ports = []

