[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu firefox libfido2 --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/firefox"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = true
dbus = false
network = "host"
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  '/usr/share/fonts:/usr/share/fonts:ro'
]
#devices = ['/dev/hidraw6', '/dev/hidraw7']
devices = []
env = ["MOZ_GTK_TITLEBAR_DECORATION=client", "MOZ_USE_XINPUT2=1"]
ports = []
args = []
