[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu firefox libfido2 libnotify --noconfirm
RUN rm -rf /var/cache/*

CMD "/usr/bin/firefox"
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
pipewire = false
dbus = false
network = "host"
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
]
fonts = true
devices = []
UsbDevices = ["1050:0116"]
env = [
	"MOZ_GTK_TITLEBAR_DECORATION=client", 
	"MOZ_USE_XINPUT2=1",
	"MOZ_WEBRENDER=1"
]
ports = []
args = []

[Run.Limits.Pids]
Limit = 8192
