[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu glava --noconfirm
RUN rm -rf /var/cache/*
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/glava"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = false
pulseaudio = true
dbus = false
net = false
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []

