[build]
image_name = 'xclock'
instructions = '''
FROM docker.io/alpine
RUN apk add --update mesa-demos xf86-video-amdgpu
RUN rm -rf /var/cache/*
CMD "/usr/bin/glxgears"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = false
dbus = false
net = false
uidmap = false
volumes = []
devices = []
env = []
ports = []

