[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu libreoffice-fresh gtk3 --noconfirm
RUN rm -rf /var/cache/*

CMD "/usr/bin/libreoffice"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = false
net = false
uidmap = true
home = true
volumes = [
  '/home/julio/.local/share/fonts:/home/user/.local/share/fonts:ro',
  '/usr/share/fonts:/usr/share/fonts:ro'
]
#volumes = []
devices = []
env = []
ports = []

