[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu base-devel git --asdeps --noconfirm

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

RUN echo '1' | gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 031F7104E932F7BD7416E7F6D2845E1305D6E801

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/librewolf-bin.git 
WORKDIR librewolf-bin

RUN pacman -S $(/bin/sh -c 'source /home/user/librewolf-bin/PKGBUILD ; echo ${depends[@]}') --noconfirm

# Workaround
RUN pacman -S ffmpeg4.4 --noconfirm

#RUN pacman -S $(/bin/sh -c 'source /home/user/librewolf-bin/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /home/user
RUN echo '1' | sudo -u user gpg --command-fd 0 --keyserver hkp://keyserver.ubuntu.com --search-keys 031F7104E932F7BD7416E7F6D2845E1305D6E801
RUN sudo -u user makepkg 
RUN pacman -U $(/bin/sh -c 'source /home/user/librewolf-bin/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm

RUN pacman -S libva-mesa-driver mesa-vdpau libfido2 --noconfirm

#RUN pacman -Rns $(/bin/sh -c 'source /home/user/librewolf-bin/PKGBUILD ; echo ${makedepends[@]}') --noconfirm-bin
WORKDIR /home/user
RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN rm -rf /var/cache/*
RUN rm -rf /home/user/librewolf-bin
CMD "/usr/bin/librewolf"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads',
  '/usr/share/fonts:/usr/share/fonts:ro'
]
devices = [
	'/dev/kfd', 
	#'/dev/hidraw1', 
	#'/dev/hidraw2',
]
args = ['--group-add', 'video']
env = [
	"MOZ_WEBRENDER=1", 
	"MOZ_USE_XINPUT2=1",
	"MOZ_DISABLE_RDD_SANDBOX=1"
	#'MOZ_LOG="PlatformDecoderModule:5"'
]
ports = []

