[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu musescore qt5-graphicaleffects qt5-quickcontrols qt5-wayland --noconfirm
RUN rm -rf /var/cache/*

CMD "/usr/bin/mscore"
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
dbus = true
network = "slirp4netns"
uidmap = true
home = true
volumes = []
devices = [
	"/dev/snd"
]
env = [
	"QT_QPA_PLATFORM=wayland-egl",
	"SDL_VIDEODRIVER=wayland",
	"XDG_SESSION_TYPE=wayland"
]
ports = []

