[build]
ContextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu base-devel git --asdeps --noconfirm
RUN pacman -S jack2-dbus pulseaudio --noconfirm

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/reaper-bin.git 
WORKDIR reaper-bin

RUN pacman -S $(/bin/sh -c 'source /home/user/reaper-bin/PKGBUILD ; echo ${depends[@]}') --noconfirm
#RUN pacman -S $(/bin/sh -c 'source /home/user/reaper-bin/PKGBUILD ; echo ${makedepends[@]}') --asdeps --noconfirm

RUN chown -R user:user /home/user
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U $(/bin/sh -c 'source /home/user/reaper-bin/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm

#RUN pacman -Rns $(/bin/sh -c 'source /home/user/reaper-bin/PKGBUILD ; echo ${makedepends[@]}') --noconfirm
#RUN pacman -Rns $(pacman -Qtdq) --noconfirm
#RUN pacman -R base-devel git --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /home/user/reaper-bin
CMD ["/usr/bin/reaper"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = false
dbus = true
net = true
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []

