[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN apt update
RUN apt dist-upgrade -y

RUN apt install gnupg software-properties-common -y
RUN add-apt-repository ppa:libretro/stable

RUN apt update
RUN apt dist-upgrade -y
RUN apt install --install-recommends retroarch* libretro-* -y

RUN apt remove gnupg software-properties-common -y
RUN apt autoremove -y
RUN apt clean -y
RUN rm -rf /tmp/*

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

WORKDIR /home/user
CMD ["/usr/bin/retroarch", "-v"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  '/home/julio/Games:/home/user/Games',
]
fonts = true
devices = []
env = []
ports = []
