[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

ADD https://getsession.org/linux /opt/session.AppImage
RUN chmod +x /opt/session.AppImage
RUN chown user:user /opt/session.AppImage

RUN pacman -S alsa-lib libnotify libxss libxtst nss libpulse libappindicator-gtk3 --noconfirm

#RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*

CMD ["/opt/session.AppImage", "--appimage-extract-and-run"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = true
dbus = true
network = "slirp4netns"
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []
