[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu signal-desktop nss libnotify --noconfirm

RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
#CMD ["/usr/bin/signal-desktop", "--disable-gpu", "--ozone-platform=wayland"]
#CMD ["/usr/bin/signal-desktop", "--start-in-tray", "--disable-gpu"]
#CMD ["/usr/bin/signal-desktop", "--use-tray-icon"]
#CMD ["signal-desktop", "--start-in-tray", "--ozone-platform=wayland"]
#CMD ["signal-desktop", "--disable-gpu", "--ozone-platform=wayland"]
CMD ["signal-desktop", "--use-tray-icon", "--ozone-platform=wayland"]
#CMD ["signal-desktop"]
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
fonts = true
volumes = [
	#"/run/user/1000:/test:ro"
]
devices = ['/dev/video0']
env = []
ports = []

