[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu signal-desktop nss libnotify --noconfirm

RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD ["/usr/bin/signal-desktop", "--start-in-tray", "--disable-gpu"]
#CMD ["/usr/bin/signal-desktop", "--start-in-tray"]
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
fonts = true
volumes = []
devices = ['/dev/video0']
env = []
ports = []

