[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN dpkg --add-architecture i386

RUN apt update
RUN apt dist-upgrade -y
RUN apt install steam lib32gcc-s1 xserver-xorg-video-amdgpu adwaita-icon-theme-full schedtool -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
RUN apt autoremove -y
RUN apt clean -y
CMD ["nice", "-n", "-10", "/usr/games/steam"]
'''

[run]
x11 = true
wayland = true
dri = true
ipc = true
pulseaudio = true
pipewire = true
dbus = true
net = true
uidmap = true
home = false
volumes = [
	"/home/julio/Games/steam:/home/user"
]
devices = [
	"/dev/kfd"
]
env = [
	"mesa_glthread=true"
]
ports = []

[Run.Limits.Pids]
Limit = 16384

