[build]
instructions = '''
FROM docker.io/archlinux

RUN echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
RUN pacman -Syu steam xorg-server xf86-video-amdgpu vulkan-radeon mesa lib32-mesa ttf-dejavu ttf-liberation pulseaudio xterm alsa-utils diffutils --noconfirm

RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN locale-gen

RUN rm -r /var/cache/pacman/pkg
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/steam-runtime"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
volumes = []
devices = []
env = []
ports = []
