[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu telegram-desktop --noconfirm
RUN rm -rf /var/cache/*

#CMD ["/usr/bin/telegram-desktop", "-startintray"]
CMD ["/usr/bin/telegram-desktop"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
volumes = [
	'/home/julio/Downloads:/home/user/Downloads',
	'/home/julio/Pictures:/home/user/Pictures:ro',
	'/home/julio/Videos:/home/user/Videos:ro',
]
devices = []
env = []
ports = []

