[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_dev

RUN pacman -Syu tiled --noconfirm
RUN rm -rf /var/cache/*

CMD "/usr/bin/tiled"
'''

[run]
name = "tiled"
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
network = "slirp4netns"
uidmap = true
home = true
fonts = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  '/home/julio/Games:/home/user/Games', 
  '/home/julio/Repos:/home/user/Repos', 
]
devices = []
UsbDevices = []
env = []
ports = []
args = []
