[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu torbrowser-launcher gtk3 --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD ["bash", "-c", "/usr/bin/torbrowser-launcher && while pgrep -f [f]irefox > /dev/null; do sleep 5; done"]
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = false
net = true
uidmap = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  #'/usr/share/fonts:/usr/share/fonts:ro'
]
devices = []
env = ["MOZ_GTK_TITLEBAR_DECORATION=client"]
ports = []
#args = ['--network', 'host']
