[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu transmission-gtk --noconfirm

RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*

CMD "/usr/bin/transmission-gtk"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = false
pulseaudio = false
dbus = false
network = "slirp4netns"
uidmap = true
home = false
volumes = ['/home/julio/Downloads:/home/user/Downloads']
devices = []
env = []
ports = ["51413:51413"]

