[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
ADD makepkg.conf /etc/makepkg.conf
ADD pacman.conf /etc/pacman.conf

RUN pacman -Syyyu flatpak-xdg-utils alsa-lib libpulse --noconfirm
RUN ln -s /usr/lib/flatpak-xdg-utils/xdg-open /usr/local/bin/xdg-open
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN locale-gen

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

RUN rm -rf /var/cache/*
CMD ["/usr/bin/bash"]
'''

[run]
