[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
ADD makepkg.conf /etc/makepkg.conf
ADD pacman.conf /etc/pacman.conf
ADD localtime /etc/localtime
ADD bin/* /usr/local/bin

RUN pacman -Syyyu schedtool --noconfirm
RUN locale-gen

RUN rm -rf /var/cache/*
CMD ["/usr/bin/bash"]
'''

[run]
