[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
ADD makepkg.conf /etc/makepkg.conf
ADD pacman.conf /etc/pacman.conf
ADD localtime /etc/localtime
ADD bin/* /usr/local/bin

RUN pacman -Syyyu schedtool hugo aws-cli ttf-hack devtools jq vim git distcc unzip ripgrep fd rust ruby ruby-bundler python python-pip nodejs npm go go-tools base-devel cmake meson ninja xdg-utils btrfs-progs wlroots flatpak-xdg-utils gdb lldb --noconfirm
RUN ln -s /usr/lib/flatpak-xdg-utils/xdg-open /usr/local/bin/xdg-open
RUN locale-gen

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
RUN echo "user ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN rm -rf /var/cache/*

WORKDIR /
'''

[run]
