[build]
contextDirectory = "/home/julio/.config/sandman/files"
instructions = '''
FROM docker.io/ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN apt update
RUN apt dist-upgrade -y

RUN apt install gnupg software-properties-common -y

ADD https://dl.winehq.org/wine-builds/winehq.key /tmp/winehq.key
RUN apt-key add /tmp/winehq.key
RUN add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'

RUN dpkg --add-architecture i386
RUN apt update
RUN apt dist-upgrade -y
RUN apt install --install-recommends winehq-stable winetricks zenity -y

RUN apt remove gnupg software-properties-common -y
RUN apt autoremove -y
RUN apt clean -y

WORKDIR /
'''

[run]

