[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu audacity --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/audacity"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = true
net = false
uidmap = true
volumes = ['/home/julio/Downloads:/home/user/Downloads', '/home/julio/Music:/home/user/Music']
devices = []
env = []
ports = []
