[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu base-devel git --asdeps --noconfirm

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

WORKDIR /home/user
RUN git clone https://aur.archlinux.org/google-chrome.git
WORKDIR google-chrome

RUN pacman -S $(/bin/sh -c 'source /home/user/google-chrome/PKGBUILD ; echo ${depends[@]}') --noconfirm

RUN chown -R user:user /home/user
RUN sudo -u user makepkg 
RUN pacman -U $(/bin/sh -c 'source /home/user/google-chrome/PKGBUILD ; echo ${pkgname}-${pkgver}-${pkgrel}-${arch}.pkg.tar.zst') --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/pacman/pkg
RUN rm -rf /home/user/google-chrome
CMD "/usr/bin/google-chrome-stable"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
volumes = []
devices = []
env = []

ports = []
