[build]
instructions = '''
FROM docker.io/archlinux
RUN pacman -Syu element-desktop noto-fonts noto-fonts-emoji --noconfirm
RUN rm -rf /var/cache/*
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/element-desktop"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = false
net = true
uidmap = true
volumes = ['/home/julio/Sandman/element:/home/user']
devices = []
env = []
ports = []
