[build]
instructions = '''
FROM docker.io/archlinux
RUN pacman -Syu firefox --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/firefox"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
volumes = ['/home/julio/Sandman/firefox:/home/user', '/home/julio/Downloads:/home/user/Downloads']
devices = []
#env = ["MOZ_ENABLE_WAYLAND=1"]
env = []
ports = []

