[build]
instructions = '''
FROM docker.io/ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN dpkg --add-architecture i386
RUN apt update
RUN apt dist-upgrade -y

ADD https://retrocdn.net/images/e/e9/Gens_2.16.8-r7orig_amd64.deb /tmp/gens.deb
RUN apt install /tmp/gens.deb -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD ["/usr/bin/gens"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = false
pulseaudio = true
dbus = false
net = false
uidmap = true
volumes = ['/home/julio/Games/genesis:/home/user']
devices = []
env = []
ports = []

