[build]
instructions = '''
FROM localhost/sandman/wine
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN dpkg --add-architecture i386

RUN apt update
RUN apt dist-upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:lutris-team/lutris

RUN apt update
RUN apt dist-upgrade -y
RUN apt install lutris -y

#RUN useradd -m --uid 1000 user
RUN apt autoremove -y
RUN apt clean -y
RUN rm -rf /var/cache/*
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD ["/usr/games/lutris"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
volumes = ['/home/julio/Games/lutris:/home/user']
devices = []
env = []
ports = []

