[build]
instructions = '''
FROM docker.io/ubuntu
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN dpkg --add-architecture i386
RUN apt update
RUN apt dist-upgrade -y
RUN apt install xserver-xorg-video-amdgpu pulseaudio libsecret-1-0 -y

ADD https://launcher.mojang.com/download/Minecraft.deb /tmp/minecraft.deb
RUN apt -f install /tmp/minecraft.deb -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

CMD "/usr/bin/minecraft-launcher"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
volumes = ['/home/julio/Games/minecraft:/home/user']
devices = []
ports = []
env = ['LANGUAGE=en_US.UTF-8']
