[build]
instructions = '''
FROM docker.io/archlinux
RUN pacman -Syu musescore --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/musescore"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = false
pulseaudio = true
dbus = true
net = true
uidmap = true
volumes = ['/home/julio/Sandman/musescore:/home/user']
devices = []
env = []

ports = []

