[build]
instructions = '''
FROM docker.io/ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN dpkg --add-architecture i386

RUN apt update
RUN apt dist-upgrade -y
RUN apt install steam xserver-xorg-video-amdgpu -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/games/steam"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
volumes = ['/home/julio/Games/steam:/home/user']
devices = []
env = ["mesa_glthread=true"]
ports = []
