[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu telegram-desktop --noconfirm
RUN rm -rf /var/cache/*
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
RUN chmod 0700 /run/user/1000
CMD "/usr/bin/telegram-desktop"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = false
pulseaudio = true
dbus = true
net = true
uidmap = true
volumes = ['/home/julio/Sandman/telegram:/home/user']
devices = []
env = []
ports = []

