[build]
instructions = '''
FROM docker.io/archlinux
RUN pacman -Syu transmission-gtk --noconfirm
RUN rm -rf /var/cache/*
RUN ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/transmission-gtk"
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = false
net = true
uidmap = true
volumes = ['/home/julio/Downloads:/home/user/Downloads']
devices = []
env = []
ports = ["51413:51413"]

