#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

while true; do
awk '
/^MemTotal:/ {
	mem_total=$2
}
/^MemAvailable:/ {
	mem_free=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	s_free=swap_free/1024/1024
	s_used=(swap_total-swap_free)/1024/1024
	s_total=swap_total/1024/1024
	free=mem_free/1024/1024
	used=(mem_total-mem_free)/1024/1024
	total=mem_total/1024/1024

	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	s_pct=0
	if (s_total > 0) {
		s_pct=s_used/s_total*100
	}

	# full text
	printf("%.f%% +%.f%%\n", pct, s_pct)

	# color
	#if (pct > 90) {
	#	print("#FF0000")
	#} else if (pct > 80) {
	#	print("#FFAE00")
	#} else if (pct > 70) {
	#	print("#FFF600")
	#}
}
' /proc/meminfo
sleep 2
done
