[build]
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu audacity ffmpeg pulseaudio pulseaudio-alsa libpulse alsa-lib --noconfirm
RUN rm -rf /var/cache/*

CMD ["high-prio", "/usr/bin/audacity"]
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = true
dbus = true
net = false
uidmap = true
fonts = true
volumes = ['/home/julio/Downloads:/home/user/Downloads', '/home/julio/Music:/home/user/Music']
devices = []
env = []
ports = []
