[build]
instructions = '''
FROM localhost/sandman/base/rocm-opencl-runtime
ADD arch_mirrorlist /etc/pacman.d/mirrorlist

# Hashcat
RUN pacman -S hashcat clinfo hcxtools --noconfirm

# Cleanup
RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*

WORKDIR /home/user
RUN chown -R user:user /home/user
CMD ["/usr/bin/bash"]
'''

[run]
x11 = false
wayland = false
dri = true
ipc = false
pulseaudio = false
dbus = false
network = "none"
uidmap = true
home = true
volumes = [
	'/home/julio/Loot:/home/user/Loot',
]
devices = ['/dev/kfd']
args = ['--group-add', 'video']
env = []
ports = []

