[build]
instructions = '''
FROM localhost/sandman/base/arch_dev

RUN pacman -S libdbusmenu-gtk3 java-runtime-common java-environment-common --noconfirm

RUN mkdir -p /tmp/build
WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/jetbrains-toolbox.git
WORKDIR jetbrains-toolbox

RUN pacman -S $(/bin/bash -c 'source /tmp/build/jetbrains-toolbox/PKGBUILD ; echo ${depends[@]}') --noconfirm

RUN chown -R user:user /tmp/build
RUN nice -n 19 sudo -u user makepkg 
RUN pacman -U *.tar.zst --noconfirm

RUN archlinux-java fix

#RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*

WORKDIR /home/user

CMD ["jetbrains-toolbox", "--appimage-extract-and-run"]
'''

[run]
name = "jetbrains"
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = false
dbus = true
network = "host"
uidmap = true
home = true
fonts = true
volumes = [
	"/home/julio/Repos:/home/user/Repos",
	"/home/julio/Projects:/home/user/Projects",
	"/home/julio/Downloads:/home/user/Downloads",
]
devices = [
	'/dev/fuse'
]
env = [
	"GOPATH=/home/user/go",
	"PATH=/home/user/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
]
ports = []

