[build]
Instructions = '''
FROM docker.io/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ADD localtime /etc/localtime

RUN apt update
RUN apt dist-upgrade -y
#RUN apt install wget gpg libnotify-bin libnotify4 libfido2-1 pipewire pulseaudio mesa-va-drivers mesa-vdpau-drivers ffmpeg vainfo adwaita-icon-theme-full xserver-xorg-video-amdgpu libglfw3 libgles2 libgles2-mesa libpci3 -y
RUN apt install wget gpg libnotify-bin libnotify4 libfido2-1 pipewire pulseaudio ffmpeg adwaita-icon-theme-full libglfw3 libgles2 libgles2-mesa libpci3 -y

RUN wget -O- https://deb.librewolf.net/keyring.gpg | gpg --dearmor -o /usr/share/keyrings/librewolf.gpg

ADD librewolf.sources /etc/apt/sources.list.d/librewolf.sources
RUN apt update
RUN apt install librewolf -y

RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
WORKDIR /home/user

RUN apt autoremove -y
RUN apt clean -y
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD "/usr/bin/librewolf"
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
pipewire = true
dbus = true
network = "slirp4netns"
uidmap = true
home = true
fonts = true
volumes = [
	"/home/julio/Downloads:/home/user/Downloads",
]
devices = [
	#'/dev/kfd', 
]
UsbDevices = ["1050:0116"]
env = [
	"MOZ_WEBRENDER=1", 
	#"MOZ_USE_XINPUT2=1",
	#"MOZ_DISABLE_RDD_SANDBOX=1",
	#'MOZ_LOG="PlatformDecoderModule:5"',
	#"mesa_glthread=true"
]
ports = []

[Run.Limits.Pids]
Limit = 8192
