[build]
Instructions = '''
FROM localhost/sandman/librewolf
CMD "/usr/bin/librewolf"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
pipewire = false
dbus = true
network = "slirp4netns"
uidmap = true
#$home = true
fonts = true
volumes = [
  #'/home/julio/Downloads:/home/user/Downloads',
]
devices = [
	#'/dev/kfd', 
]
UsbDevices = ["1050:0116"]
env = [
	"MOZ_WEBRENDER=1", 
	"MOZ_USE_XINPUT2=1",
	"MOZ_DISABLE_RDD_SANDBOX=1",
	'MOZ_LOG="PlatformDecoderModule:5"',
	"mesa_glthread=true"
]
ports = []

