[build]
instructions = '''
FROM docker.io/archlinux
ADD arch_mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Syu retroarch retroarch-assets-glui retroarch-assets-ozone retroarch-assets-xmb libretro-overlays libretro-shaders python libxrandr libxinerama xf86-video-amdgpu vulkan-radeon vulkan-icd-loader --noconfirm
RUN rm -rf /var/cache/*
RUN useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000
CMD "/usr/bin/retroarch"
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
network = "slirp4netns"
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
  '/home/julio/Games:/home/user/Games',
  '/usr/share/fonts:/usr/share/fonts:ro',
]
devices = []
env = []
ports = []
args = []
