[build]
instructions = '''
FROM localhost/sandman/base/arch_build

# esbuild
WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/esbuild.git 
WORKDIR esbuild
RUN yes | nice -n 19 makepkg -si --noconfirm

# webcord
WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/webcord.git 
WORKDIR webcord
RUN yes | nice -n 19 makepkg -si --noconfirm

# Cleanup
WORKDIR /home/user
RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*

# Cleanup
WORKDIR /home/user
RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*

CMD ["/usr/bin/webcord", "--ozone-platform=wayland"]
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
dbus = true
network = "slirp4netns"
uidmap = true
home = true
fonts = true
volumes = [
	'/home/julio/Downloads:/home/user/Downloads', 
	'/home/julio/Pictures:/home/user/Pictures:ro', 
	'/home/julio/Pictures:/home/julio/Pictures:ro', 
	'/home/julio/Videos:/home/user/Videos:ro',
	'/home/julio/Videos:/home/julio/Videos:ro',
]
devices = ['/dev/video0']
args = []
env = []
ports = []

