[build]
instructions = '''
FROM localhost/sandman/base/wine
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN id 1000 || useradd -m --uid 1000 user
RUN mkdir -p /run/user/1000/pulse
RUN chown -R user:user /run/user/1000

RUN apt autoremove -y
RUN apt clean -y
CMD ["/usr/bin/wine", "explorer"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = true
uidmap = true
home = false
volumes = [
	"/home/julio/Downloads:/home/user/Downloads"
]
devices = []
env = []
ports = []

