[build]
instructions = '''
FROM docker.io/kalilinux/kali-rolling
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN apt update
RUN apt dist-upgrade -y
RUN apt autoremove -y
RUN apt clean -y
RUN rm -rf /var/cache/*

WORKDIR /root
CMD ["/usr/bin/bash"]
'''
