[build]
instructions = '''
FROM localhost/sandman/base/kalitools
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

RUN apt install burpsuite -y

RUN useradd -m --uid 1000 user
RUN apt autoremove -y
RUN apt clean -y
RUN rm -rf /var/cache/*
RUN mkdir -p /run/user/1000
RUN chown -R user:user /run/user/1000

CMD ["/usr/bin/burpsuite"]
'''

[run]
x11 = true
wayland = false
dri = false
ipc = true
pulseaudio = false
dbus = false
net = true
uidmap = false
volumes = []
devices = []
env = [
	"_JAVA_AWT_WM_NONREPARENTING=1"
]
ports = ['8080:8080']

