[build]
instructions = '''
FROM localhost/sandman/base/arch_dev

RUN pacman -Syu emacs --noconfirm

WORKDIR /home/user

RUN rm -rf /tmp/*
RUN rm -rf /var/cache/*
CMD "/usr/bin/emacs"
'''

[run]
name = "emacs"
x11 = true
wayland = false
dri = false
ipc = false
pulseaudio = false
dbus = false
network = "slirp4netns"
uidmap = true
home = true
volumes = [
	"/usr/share/fonts:/usr/share/fonts:ro",
	'/home/julio/.local/share/fonts:/home/user/.local/share/fonts:ro',
	"/home/julio/Repos:/home/user/Repos",
	"/home/julio/Repos/dotfiles/.doom.d:/home/user/.doom.d",
	"/home/julio/Projects:/home/user/Projects",
	"/home/julio/Downloads:/home/user/Downloads",
	#"/home/julio/Kali:/home/user/Kali",
]
devices = []
env = [
	"GOPATH=/home/user/go",
	"PATH=/home/user/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
]
ports = []
args = []
