[build]
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu firefox ffmpeg libfido2 libnotify libva-mesa-driver libva-utils speech-dispatcher --noconfirm
#RUN pacman -Syu firefox libfido2 libnotify --noconfirm
RUN rm -rf /var/cache/*

CMD "/usr/bin/firefox"
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
pipewire = true
dbus = true
network = "host"
uidmap = true
home = true
volumes = [
  '/home/julio/Downloads:/home/user/Downloads', 
]
fonts = true
devices = [
	"/dev/kfd"
]
UsbDevices = ["1050:0116"]
env = [
	"MOZ_GTK_TITLEBAR_DECORATION=client", 
	#"MOZ_USE_XINPUT2=1",
	"MOZ_WEBRENDER=1"
]
ports = []
args = []

[Run.Limits.Pids]
Limit = 8192
