[build]
instructions = '''
FROM localhost/sandman/base/arch_build

RUN echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
RUN pacman -Syu schedtool pulseaudio pulseaudio-alsa lib32-mesa lib32-libpulse lib32-alsa-lib lib32-alsa-plugins --noconfirm

WORKDIR /tmp/build
RUN git clone https://aur.archlinux.org/kega-fusion.git 
WORKDIR kega-fusion
RUN low-prio makepkg -si --noconfirm

RUN pacman -Rns $(pacman -Qtdq) --noconfirm
RUN rm -rf /var/cache/*
RUN rm -rf /tmp/*
CMD ["/usr/local/bin/high-prio", "/usr/bin/kega-fusion"]
'''

[run]
x11 = true
wayland = false
dri = true
ipc = true
pulseaudio = true
dbus = false
net = false
uidmap = true
fonts = true
volumes = ['/home/julio/Games/genesis:/home/user']
devices = []
env = []
ports = []

