[build]
instructions = '''
FROM localhost/sandman/base/arch_user

RUN pacman -Syu telegram-desktop qt6-wayland --noconfirm
RUN rm -rf /var/cache/*

#CMD ["/usr/bin/telegram-desktop", "-startintray"]
CMD ["/usr/bin/telegram-desktop"]
'''

[run]
x11 = false
wayland = true
dri = true
ipc = true
pulseaudio = true
dbus = true
net = true
uidmap = true
home = true
fonts = true
volumes = [
	'/home/julio/Downloads:/home/user/Downloads',
	'/home/julio/Pictures:/home/user/Pictures:ro',
	'/home/julio/Videos:/home/user/Videos:ro',
]
devices = []
env = [
	"QT_QPA_PLATFORM=wayland-egl",
	"SDL_VIDEODRIVER=wayland",
	"XDG_SESSION_TYPE=wayland"
]
ports = []

