#!/bin/sh

card=/sys/class/drm/card0/device

#usage=$(cat $card/gpu_busy_percent)
memory_total=$(cat $card/mem_info_vram_total)
memory_used=$(cat $card/mem_info_vram_used)
percent=$(awk "BEGIN { pc=100*${memory_used}/${memory_total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")

echo ${percent}%
